### ISSUE TITLE
Fix pi-cross hints are only grayed out when the line is full, not when they match the hints

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#106]
For example, in a 5x5 puzzle, a column is only marked as filled when there are 5 filled boxes, even if the hint is just 1. Instead, the hint should be grayed out when the filled in boxes exactly match the hints.

**Comment by AEFeinstein** [comment]
@hunterdyar more context

**Comment by hunterdyar** [comment]
See my other comment on the PR. There are reasons to have it work the way it currently does. The short version is that mark-empties are information the user may need to progress, and fading implies the user should direct attention elsewhere, misleading them. Yet correct filling is also feedback that we want to give the user. I think one design solution is multiple levels of fade for "correctly filled" and "completely filled".
