### ISSUE TITLE
MFPaint

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#114]
Major must-have TODOs:
- [x]  Tool icons instead of text
- [x] Multiple save-slots
- [x] Load/save UI
- [x] Color picking UI
- [x] Implement sharing
- [x] Improve cursor design, possibly with sprites?
- [x] Gallery / carousel screen
- [x] Tutorial screen
- [x] Fix crash and weird behavior of squarewave brush

Must-have polish:
- [x] Prevent tutorial mode from getting out of sync with screen state
- [x] Add touchpad into tutorial
- [x] Prevent or handle share-->share and receive-->receive connections
- [ ] ~Change background color to be a bit less plain~ working as intended
- [x] Fix D-pad sometimes sticking
- [x] Fix A presses sometimes getting skipped
- [x] Use touchpad instead of select for swapping colors/tools (thumb covers the screen...)
- [x] Test out using touchpad and D-pad instead of select and D-pad for editing palette (up/down for colors, left/right for R/G/B, X/Y for channel value down/up)
- [x] Use touchpad for brush size
- [x] Fix cursor overlapping border, sometimes
- [x] Parameterize default cursor size / alignment to canvas scale
- [x] Fix color palette potentially being drawn off-screen (happens in tutorial)
- [x] Temporarily display time when changing speed in gallery mode
- [x] Better contrast for selected color when changing colors
- [x] Fix cursor disappearing after clearing canvas

Nice-to-haves:
- [x] Stroke width for line-based brushes
- [x] Background music
- [ ] A theme-related "default" image
- [x] Polygon tool in tutorial
- [x] Use gallery as screensaver from paint menu
- [ ] Airbrush tool
- [ ] Changeable background color in zoomed-out gallery mode
- [ ] Gallery 2x2 mode
- [x] Do something with LEDs in gallery?
- [x] Use different cursors per brush
- [x] Add tool name text at bottom of screen?
- [ ] Use the same font everywhere maybe?
- [x] Improve cursor contrast
- [x] LED color matching (+ settings page)
- [x] Blink pick points
- [x] 'Exit' option on draw mode save menu
- [x] 'Unsaved' warning
- [x] Display last saved/loaded slot in draw mode
- [ ] ~Color picker tool~ Not really needed, there's only 16 colors
- [ ] ~Text or char stamp tool~ Not gonna implement font scaling

Stretch:
- [ ] Copy/paste
- [ ] Collaborative drawing mode
- [ ] ~Undo or quicksave (with its own dedicated slot)~ Not enough space!

Minor bugs:
- [x] Pressing and releasing select should never change the foreground color without moving up/down, i.e. swapping fg colors should also rearrange the palette
- [x] Circle pen seems a bit big at its smallest (but is not a circle if it's smaller)

**Comment by AEFeinstein** [comment]
I don't think I meant to close this after merging. @dylwhich wanna check off the stuff you did? It's _gotta_ be pretty close to done at this point.

**Comment by arty01238** [comment]
I think an implementation to adjust brush size using the touchpad would be a nice addition to the swadge!

**Comment by AEFeinstein** [comment]
It's pretty straightforward to get those events, see `.fnTouchCallback = gamepadTouchCb,` for an example. `evt->position` is just an 8 bit number!

**Comment by dylwhich** [comment]
Ooh, that would be perfect! SELECT+A/B is a bit awkward and I couldn't think what to do with the touchpad...

**Comment by AEFeinstein** [comment]
Aside from touch stuff, is there anything else you're considering for Paint, or is it pretty much done? Feels pretty much done to me, but I'm not the author!

**Comment by dylwhich** [comment]
There's still a couple things I want to work on, but nothing too major

* I need to finish polishing up the tutorial so you can't get it out of sync
* If it's reasonably straightforward, I want to add a width option to the line-based drawing tools
* I need to follow up on BGM still
* Some more UI polish, especially with the tool info and picker cursor

**Comment by AEFeinstein** [comment]
Sounds good to me. You know when freeze is!
