### ISSUE TITLE
Port Techno Slide Whistle

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#127]
- [x] Get code running on ESP32-S2
- [x] Color
- [x] Resize everything for the larger screen (no more tiny font)
- [x] Resize bars, ticks, cursor?
- [x] Fix roll
- [x] Rotate all axes by 90 degrees (from "ship wheel" to "game controller / the way it sits on a table") (this is close enough, thanks Adam!)
- [x] Think up something for B to do (Kevin says: hold note?)
- [x] Multiple octaves, switch via Up and Down on d-pad (add one more C to C at the end of each scale - DUPLICATE C's BETWEEN BARS)
  - Up: high octave
  - None: mid octave
  - Down: low octave
- [x] Probably should have button labels
- [x] (Optional) Change modifier buttons to work with d-pad instead of accelerometer
- [x] Fix/alter arps/scales (Dac will do this) (Does the "Dac" scale need extra C notes from the next octave at the end of each line?)
- [x] Touch pad mode
  - Replace both the A button and accelerometer with touch pad
  - Overrides accelerometer
- [x] Fix hardware freeze when pressing A
- [x] Fix "slide" mode sounding rough
- [x] Fix scale bar ticks not being consistently spaced

**Comment by AEFeinstein** [comment]
I ran this and captured the backtrace from the UART output:
```
task_wdt_isr at task_wdt.c:183 (discriminator 3)
_xt_lowint1 at xtensa_vectors.S:1111
vPortClearInterruptMaskFromISR at portmacro.h:571
 (inlined by) vPortExitCritical at port.c:319
 (inlined by) vPortExitCritical at port.c:304
xQueueSemaphoreTake at queue.c:1630
rmt_wait_tx_done at rmt.c:1169 (discriminator 2)
buzzer_stop at musical_buzzer_rmt.c:342 (discriminator 1)
slideWhistleBeatTimerFunc at mode_slide_whistle.c:1379
timer_process_alarm at esp_timer.c:360
 (inlined by) timer_task at esp_timer.c:386
```
There's something fishy here:
```C
// Spin and wait for any ongoing transmissions to finish
while (ESP_ERR_TIMEOUT == rmt_wait_tx_done(rmt_buzzer.channel, 0))
{
    ;
}
```
My initial thought was that it doesn't like an infinitely long note, but I
see you have it set to 1s:
```C
slideWhistle->song.notes[0].note = C_0;
slideWhistle->song.notes[0].timeMs = 1000;
slideWhistle->song.numNotes = 1;
slideWhistle->song.shouldLoop = true;
```
Hm

**Comment by AEFeinstein** [comment]
I ran this and captured the backtrace from the UART output:
```
task_wdt_isr at task_wdt.c:183 (discriminator 3)
_xt_lowint1 at xtensa_vectors.S:1111
vPortClearInterruptMaskFromISR at portmacro.h:571
 (inlined by) vPortExitCritical at port.c:319
 (inlined by) vPortExitCritical at port.c:304
xQueueSemaphoreTake at queue.c:1630
rmt_wait_tx_done at rmt.c:1169 (discriminator 2)
buzzer_stop at musical_buzzer_rmt.c:342 (discriminator 1)
slideWhistleBeatTimerFunc at mode_slide_whistle.c:1379
timer_process_alarm at esp_timer.c:360
 (inlined by) timer_task at esp_timer.c:386
```
There's something fishy here:
```C
// Spin and wait for any ongoing transmissions to finish
while (ESP_ERR_TIMEOUT == rmt_wait_tx_done(rmt_buzzer.channel, 0))
{
    ;
}
```
My initial thought was that it doesn't like an infinitely long note, but I
see you have it set to 1s:
```C
slideWhistle->song.notes[0].note = C_0;
slideWhistle->song.notes[0].timeMs = 1000;
slideWhistle->song.numNotes = 1;
slideWhistle->song.shouldLoop = true;
```
Hm

**Comment by AEFeinstein** [comment]
Seems to be better if you modify the buzzer functions to track if something is playing or stopped, and don't try stopping if it's already stopped. Still not great.

**Comment by AEFeinstein** [comment]
>  Fix "slide" mode sounding rough

@Brycey92 this is done, right? The other to-dos are accurate?

**Comment by Brycey92** [comment]
> > Fix "slide" mode sounding rough
> 
> @Brycey92 this is done, right? The other to-dos are accurate?

Correct, and correct. Just added the check mark, and I can copy over Dac's new UI/UX design plan for the mode too

**Comment by AEFeinstein** [comment]
Didn't realize there's a new UI/UX plan. Neat.

**Comment by AEFeinstein** [comment]
Does the accelerometer still need any work? Felt pretty good to me last test.

**Comment by Brycey92** [comment]
I'd love it to act more like tilting a game controller held flat than like a steering wheel

**Comment by Brycey92** [comment]
Current tilt axis:
![current tilt axis](https://user-images.githubusercontent.com/666399/197420592-419b9e2d-1ba4-4107-9588-93519d095ece.png)

Proposed tilt axis:
![proposed tilt axis](https://user-images.githubusercontent.com/666399/197420734-71f4b53a-f8eb-44e5-bd05-acdddfc75e5e.png)

**Comment by AEFeinstein** [comment]
I thought on this, and I like it more as a steering wheel. Ergonomically I find it easier, faster, and more comfortable to rotate a swadge like a steering wheel rather than a flat game controller. What's the argument for flat controller? How did the Barrel work?

**Comment by Brycey92** [comment]
The barrel works at a 45 degree angle optimally (like one would hold a phone), tilted in either of those axes above. It can also be used completely flat or completely vertically, like in the images above, though you'll only be in one octave if you're not holding it like a phone at roughly 30-60 degrees.

**Comment by Brycey92** [comment]
The accel experience is definitively worse on this version of the swadge :(

**Comment by AEFeinstein** [comment]
Should be better after https://github.com/AEFeinstein/Super-2023-Swadge-FW/commit/90585da9d26b6a40243db2eb342ccb57387eec14. [`techno-slide-whistle`](https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/techno-slide-whistle) is all merged. @Brycey92 still planning on more work this week, or is this all good to go?

**Comment by Brycey92** [comment]
Dac still needs to get those fixed arpeggios, but those can happen during the bugfixes-only stage since that involves changing numbers in an array of notes.

**Comment by AEFeinstein** [comment]
Gotcha, sounds good. I'll poke Dac.

**Comment by Brycey92** [comment]
Dac's stuff is merged!
