### ISSUE TITLE
Pi-cross

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#158]
Aside from adding more puzzles, are there any engine-level features or bugs you're looking at? If so, please succinctly list them here. If not, you can close this ticket and delete the branch (https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/picross). I'm comfortable adding puzzles directly to `main`.

**Comment by hunterdyar** [comment]
engine-level stuff is just audio and LED things. I don't play any significant changes. Gotta get the pi symbol in.

For reference, i'll put all my [todos](https://superficial-jingle-d4a.notion.site/Picross-Swadge-dbc9531e2e5f4039b8fa579460d7177e) here, although some is low-level and wont get done.

- pi symbol in font.
- Implement Audio (particularly: rick-roll music on solving just that level)
- Explore performance impact of intermittent saving, implement if possible
- Run UI through colorblind tests
- Create victory LED Dance animation, or cut LEDs entirely
- Make menu B button behave consistently with swadge ux
- Put erase-all-progress back in options?
- put "are you sure" in erase progress/erase all progress options?
- Increase DAS speed slightly

Level Work
- Level 10 needs fixed/replaced
- more levels!
- check level titles don't extend off-screen on victory pages (figure out max char count and check for it)

Later work: 
- Recapture screenshots for the how-to-play page with new 'x' UI

**Comment by AEFeinstein** [comment]
https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/picross is all merged up, but I think you still wanted music, and maybe some of those unchecked boxes? Just a reminder that it's the last week before freeze!
