### ISSUE TITLE
Dice Roller

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#192]
## Necessary

- [x] Don't start on 0d0
- [x] Fix cursor shape and position (maybe use a sprite instead of lines?)
- [x] The new "Total" value flashes briefly then is cleared when the dice start rolling rather than only being shown when the die stop
- [x] Have `B` button roll dice too, unless you can think of a better thing for it to do

## Optional

- [x] Colorize it, see `oddEvenFill()` to fill polygons
- [ ] Randomize different numbers per-die when rolling rather than having them all be the same number
- [x] Display history, like "1d6: 4, 2d8: 10" maybe in a vertical list. Maybe press `B` to swap between roll history and dice?

**Comment by AEFeinstein** [comment]
@ScrumpySipper feel free to fill this out if you have other ideas or tasks

**Comment by ScrumpySipper** [comment]
All necessary changes fixed on diceRollerFixes branch. Will hop on option changes tomorrow or next day. Do you think it would be necessary to have history remember the state of each die in a roll or just the total? Also, colorizing/sprites will take me a bit to familiarize myself with.

**Comment by AEFeinstein** [comment]
Great progress!

History can just be the total, not each die.

Sprites are not necessary if you already fixed the cursor. They're simple to use though and there are examples everywhere. You can also ask in slack for a hand there. 

Filling a shape uses this algorithm
https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule
If memory serves, you draw your shape, then call the function with the square bounds around your shape to fill it, then draw text over the fill. Melee menu does it, for an example.

**Comment by ScrumpySipper** [comment]
The branch now contains code to fill the dice with a solid color. Due to how the polygons are drawn, there can be horizontal rows with single pixels or places where the outline is 2 pixels thick. I implemented a modification of oddEvenFill called oddEvenFillFix which can fill empty convex shapes with arbitrarily thick outlines or horizontal rows containing outline without need for fill. This is definitely much slower than the normal oddEvenFill, so I might switch to using sprites. Do you know how to paint background images (ideally a tileable wooden tabletop texture here) without significant performance hits? I'm having trouble finding how it's implemented in the fighter.

**Comment by dylwhich** [comment]
There's an implementation of flood-fill for MFPaint [here](https://github.com/AEFeinstein/Super-2023-Swadge-FW/blob/main/main/modes/paint/paint_brush.c#L12) which might work for your use-case. The implementation is supposedly fairly optimized but I've never actually tried using it as part of the rendering cycle.

If that performs OK for you, I'll move it into `bresenham.h` and get it merged into main. Actually, I should probably do that regardless...

**Comment by AEFeinstein** [comment]
Just to start, you're rolling dice, and you really don't have to be worrying about performance unless you're doing something really wrong (which you aren't). The ESP32-S2 has horsepower! Don't be afraid to lean on it.

> I implemented a modification of oddEvenFill called oddEvenFillFix which can fill empty convex shapes with arbitrarily thick outlines or horizontal rows containing outline without need for fill.

lol, I don't know how late it was when I wrote this gem:
```
WARNING!!! This is very finicky and is not guaranteed to work in all cases.
```
As a personal exercise I tried to make `oddEvenFill()` work better in more cases. I did this without looking at 7fb7d8337a48c7200fbbab19dc24598c550d5e4a. I don't think it's meaningfully slower (three branches per loop). You're free to use it if it works for you:
```C
void oddEvenFill(display_t* disp, int x0, int y0, int x1, int y1,
                 paletteColor_t boundaryColor, paletteColor_t fillColor)
{
    // Enum declaration to be used later
    typedef enum {
        OE_OUTSIDE,
        OE_BOUNDARY_GOING_IN,
        OE_INSIDE,
        OE_BOUNDARY_GOING_OUT
    } oddEvenState_t;

    SETUP_FOR_TURBO( disp );

    // Adjust the bounding box if it's out of bounds
    if(x0 < 0)
    {
        x0 = 0;
    }
    if(x1 > disp->w)
    {
        x1 = disp->w;
    }
    if(y0 < 0)
    {
        y0 = 0;
    }
    if(y1 > disp->h)
    {
        y1 = disp->h;
    }

    // Iterate over the bounding box
    for(int y = y0; y < y1; y++)
    {
        // Assume starting outside the shape for each row
        oddEvenState_t oe = OE_OUTSIDE;
        // start this as some not-boundaryColor
        paletteColor_t prevPixel = boundaryColor + 1;
        // Iterate across the row
        for(int x = x0; x < x1; x++)
        {
            paletteColor_t currPixel = GET_PIXEL(disp, x, y);
            // If a boundary is being entered
            if(boundaryColor != prevPixel && boundaryColor == currPixel)
            {
                // Pick the boundary state based on the current state
                if(oe == OE_OUTSIDE)
                {
                    oe = OE_BOUNDARY_GOING_IN;
                }
                else
                {
                    oe = OE_BOUNDARY_GOING_OUT;
                }
            }
            // If a boundar is being exited
            else if(boundaryColor == prevPixel && boundaryColor != currPixel)
            {
                // Pick the inside/outside state based on the current state
                if(oe == OE_BOUNDARY_GOING_IN)
                {
                    oe = OE_INSIDE;
                }
                else
                {
                    oe = OE_OUTSIDE;
                }
            }
            
            // If we're in-bounds, color the pixel
            if(OE_INSIDE == oe)
            {
                TURBO_SET_PIXEL_BOUNDS(disp, x, y, fillColor);
            }
            prevPixel = currPixel;
        }
    }
}
```

> Do you know how to paint background images (ideally a tileable wooden tabletop texture here) without significant performance hits?

Yes I do, and the magic is `.fnBackgroundDrawCallback`. Create a function, set that in the mode struct, and the system will call it when it's time to draw a portion of the background. It is not called for the whole background in one shot. Looking at the source, it's done in 280x16 px slices. This is a consequence of how `drawDisplayTft()` uses DMA to send one buffer of TFT data while filling another. Note that if you use this callback you *must* redraw the whole scene each time your `.fnMainLoop` is called.

As far as tiling a texture, in general, `loadWsg()`, `drawWsgSimpleFast()`, and `freeWsg()` are used for images. Just make sure your image is in the `assets` folder first and the build should take care of converting and packing it. You get to figure out math and boundaries and that kind of stuff. It shouldn't be bad if your texture is 16px tall (or you use two textures to make a 32px tiled texture).

Also remember that you're limited to the web safe color palette. The converter will resample and dither images automatically, but you may not get really great colors for wood.

For reference:
```C
/**
 * This function is called when the display driver wishes to update a
 * section of the display.
 *
 * @param disp The display to draw to
 * @param x the x coordiante that should be updated
 * @param y the x coordiante that should be updated
 * @param w the width of the rectangle to be updated
 * @param h the height of the rectangle to be updated
 * @param up update number
 * @param numUp update number denominator
 */
void (*fnBackgroundDrawCallback)(display_t* disp, int16_t x, int16_t y, int16_t w, int16_t h, int16_t up,
								 int16_t upNum );
```

**Comment by ScrumpySipper** [comment]
Added background wood texture, marginally more pleasant dice, and a history log along the left margin to branch. Please weigh in on how the history log looks as-is and whether it seems necessary to move it into its own menu in the state machine.

**Comment by AEFeinstein** [comment]
I like the wood, and the history doesn't need to be moved into it's own menu.

It does feel imbalanced, so I'd recommend moving the dice to the right and spacing them out a little more. With the extra space you can also add a space to the history entry like `6d12: 50` instead of `6d12:50`. It's a little hard to read when it's so tight.

![image](https://user-images.githubusercontent.com/231180/198862826-2aa971ab-6c2c-473f-9f0e-49c6c496abbd.png)

**Comment by ScrumpySipper** [comment]
I rebalanced the display and changed the selection cursor to a little golden sprite 
![newDisplay](https://user-images.githubusercontent.com/93800683/198864345-4f7508d1-3832-4b5b-83a1-8c104b9ddae3.PNG)

**Comment by ScrumpySipper** [comment]
![diceRollerUI2](https://user-images.githubusercontent.com/93800683/198865617-6086f110-318a-46c2-a5d5-306081240812.PNG)

**Comment by ScrumpySipper** [comment]
Okay I think I'm comfortable with the state of this mode now

**Comment by AEFeinstein** [comment]
Oh yeah, I like the look of that!

**Comment by AEFeinstein** [comment]
@ScrumpySipper PR merged. Is this good to close?

Also don't forget to put your name in the credits
https://docs.google.com/forms/d/e/1FAIpQLSeEfgAl3xgTlYi8ixvJD_MFG-SOUfdU0OcD_HtRUyjUc6XnqA/viewform?usp=sf_link
