### ISSUE TITLE
Main menu secretSong sounds weird

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#235]
Someone speculated that the song arpeggiates notes too frequently. The line to play the song is currently commented out until the issue is fixed.

**Comment by AEFeinstein** [comment]
It doesn't sound that good in the emulator either. I don't know where you got it, but maybe replace it wholesale with something from Fawful or Bedrock?

**Comment by Brycey92** [comment]
I think I got it from sirocyl, will ask one of the others for a swadge-ified version

**Comment by Brycey92** [comment]
Closed by #258
