### ISSUE TITLE
Fix jumpy text in wrappy-bees-2 branch

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#236]
Steps to reproduce:

1. On main menu, press: Up, Up, Down, Down, Left, Right, Left, Right, B, A, Start
2. Select "Alice"
3. Wait for text to scroll

**Comment by dylwhich** [comment]
Okay, so far I was able to fix the jumping at the expense of scrolling up, but I'll see if I can fix that too.

**Comment by dylwhich** [comment]
It's fixed! In a much less hacky and confusing way than before, too! And also it works in both directions, and it doesn't even matter if a single line of text doesn't fit on the screen. You can even use the main menu font if you want!
