### ISSUE TITLE
Add recent songs/sfx to jukebox

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#237]
@AEFeinstein says he did this, but we should keep doing this as music or sfx are added.

**Comment by AEFeinstein** [comment]
Pulled in latest Platformer stuff too

https://github.com/AEFeinstein/Super-2023-Swadge-FW/commit/d680ccb0ae145d64eda19c38eb256363114e305c#diff-f6e70512dcea6a372a5eb97d2af8bc3f6eaea061d93ab9a2128e637ccbb10770

**Comment by AEFeinstein** [comment]
Manually checked and all but two songs are accounted for `BlackDog` (copyright) and `secretSong` (doesn't have an unlock mechanism the way `picross_music_rick` does).

**Comment by Brycey92** [comment]
Oh, did you disable BlackDog and the test mode entry in jukebox?

**Comment by AEFeinstein** [comment]
Yes, in 4ed42da92ac7eff7b20123f6aa701765750d2491
