### ISSUE TITLE
Create Test Mode

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#24]
- [x] Play a known tune / frequency sweep on the buzzer
- [x] Listen for that tune / sweep on the mic, set the pass condition when detected
- [x] Set the pass condition when all buttons are pressed and released once
- [x] Set the pass condition when all segments of the touchpad are touched
- [x] Add a note on TFT to check LED behavior
- [ ] Display git hash
- [x] Save result to NVM, don't boot into test mode if the result exists
- [x] Detect an accelerometer shake

**Comment by Brycey92** [comment]
See #29 for suggestion about reusing code between here and gamepad mode
