### ISSUE TITLE
Look into buzzer skipping notes and/or looping songs too early

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#243]

**Comment by AEFeinstein** [comment]
I recorded the song in question, measured the waveform, and all the timings are correct. The buzzer isn't skipping or looping too early. The specific problem with `paintBgm` is that it ends on a note and begins on a note without a `SILENCE` in between (like the rest of the songs). The loop is where the vertical bar is:
![image](https://user-images.githubusercontent.com/231180/200757120-c01b2dce-74c1-4a04-b1d3-47757630a577.png)
I'll add a little `SILENCE` at the end of the tune for a smoother loop.
