### ISSUE TITLE
Sub-menu return navigation consistency

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#246]
In some sub-menus, pressing B or selecting Back will return you to the top menu with the previous menu item (i.e. the submenu) still selected. In others, the first menu item is selected.

Sub-menus that return with previous option selected:
* All main menu submenus
* MFPaint submenus and gallery
* Pi-cross "How To Play" screen

Sub-menus that return with first option selected:
* Swadge Bros submenus
* Pi-cross Puzzle Select and Options submenus

**Comment by dylwhich** [comment]
One more thing that I think fits here - MFPaint lets you use B to exit the mode from the menu, but it's the only one that does it and should probably be removed. Or, if it's not too feature-like, we could make pressing B once select the "Exit" menu item, and then if "Exit" is already selected, pressing B will actually exit.

**Comment by AEFeinstein** [comment]
I say remove it. Simple. There's real time spent entering and exiting
modes, and incurring that accidentally doesn't feel great.

**Comment by dylwhich** [comment]
Alright, I'll add that as a separate issue and remove it.

**Comment by AEFeinstein** [comment]
Swadge Bros. had an annoying number of menus
