### ISSUE TITLE
Option indicator LEDs do not turn off after leaving melee menu

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#247]
I don't think this is easily fixable from within the melee menu itself, but the LEDs that change with the selected menu option do not turn off when entering a submenu that's in the same mode. Also worth noting that for whatever reason, this doesn't happen on the emulator.

This affects:
* Swadge Bros "Connecting..." screens
* Swadge Bros "Records" screen
* Pi-Cross game - LEDs stay on when you enter the game, and will only be cleared if "Mistake Alert" is enabled and you make a mistake
* Pi-Cross Puzzle Select
* Pi-Cross How To Play

Simple fix is to just do this once when leaving the menu for a screen that doesn't use LEDs itself:

    led_t leds[NUM_LEDS];
    memset(leds, 0, sizeof(led_t) * NUM_LEDS);
    setLeds(leds, NUM_LEDS);

**Comment by AEFeinstein** [comment]
I experimented by turning LEDs off before calling the callback in melee menu, and while that works, you do get a little flicker when entering another melee menu submenu. I don't like it. It just has to be handled any time the melee menu is no longer shown.
