### ISSUE TITLE
Tiltrads main menu button presses do not always register

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#248]
It seems fine in game, but in the main menu it feels like I have to really hold the button down for a long time to actually get it to register.

**Comment by dylwhich** [comment]
Ohhhhh, I bet this is because of the start/select button sending delay. I think it may be entirely consuming button presses that are shorter than the delay time.

**Comment by AEFeinstein** [comment]
There is a slight delay on start & select to register as an individual button press rather than a combo, but it shouldn't be throwing single presses into the void.

**Comment by AEFeinstein** [comment]
The button events are getting passed to tiltrads just fine, you can see it with this change:
```C
void ttButtonCallback(buttonEvt_t* evt)
{
    printf("%s %02X %02X\n", evt->down ? "down" : " up ", evt->button, evt->state);
    tiltrads->ttButtonState = evt->state;  // Set the state of all buttons.
}
```
The problem is the button is setting and unsetting faster than `ttUpdate()` can notice that it was pressed.
