### ISSUE TITLE
Finalize Modes

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#25]
## Games
| Mode          | Owner        | Branch                                                              |
| ------------- | ------------ | ------------------------------------------------------------------- |
| Fighter       | @AEFeinstein | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/fighter    |
| Platformer    | @JVeg199X    | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/platformer |
| QJumper       | @MrTroyD     | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/qjumper    |
| Tiltrads Port | @jt-moriarty | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tiltrads   |

## Tools
| Mode           | Owner        | Branch                                                              |
| -------------- | ------------ | ------------------------------------------------------------------- |
| ~~Colorchord~~ | ~~@AEFeinstein~~ | ~~https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/colorchord~~ |
| ~~Gamepad~~    | ~~@AEFeinstein~~ | ~~https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/gamepad~~    |
| Tunernome Port | @Brycey92    | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tunernome  |
| Credits        | @AEFeinstein | https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/credits    |
| LED Animations | ???          | none yet                                                            |
| Instrument?    | ???          | none yet                                                            |

**Comment by Brycey92** [comment]
- Light dances
- Ports of old games/modes

and yes, I need to get to porting Tunernome lol

**Comment by AEFeinstein** [comment]
My preference is new stuff over ports, but yes, tunernome makes the cut.

**Comment by AEFeinstein** [comment]
@jt-moriarty what are the odds you'll make your racer?
