### ISSUE TITLE
Donut Jump: Pressing any direction button resets the dying animation

### ISSUE THREAD

**Issue by dylwhich** [AEFeinstein/Super-2023-Swadge-FW#279]
Steps to reproduce:
* Open Donut Jump
* Pick Jump in the menu
* Move to somewhere so that an enemy will jump to you
* Hold one of the D-pad directions
* When the enemy lands on you, nothing will happen.
* Release the button momentarily. The animation will continue
* Press a D-pad button again. The animation will reset.
* This can be repeated indefinitely.

**Comment by AEFeinstein** [comment]
@MrTroyD can you look into this super quickly?

**Comment by MrTroyD** [comment]
On it.

**Comment by dylwhich** [comment]
Fixed by #280
