### ISSUE TITLE
Add visuals for Gamepad

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#29]

**Comment by Brycey92** [comment]
We could share some code/design between test mode and gamepad mode, if we make gamepad mode a visual representation of all the inputs (buttons, mic, slider). That's basically what test mode is, but each mode here would have a couple extra bits.

**Comment by AEFeinstein** [comment]
We can probably have the slider act as one axis of an analog stick. I wasn't planning on having the mic be an input, so that wouldn't be a gamepad visual. I'll worry about code-reuse between test and gamepad modes, but it'll likely be relatively small.
```C
/// HID Gamepad Protocol Report.
typedef struct TU_ATTR_PACKED
{
  int8_t  x;         ///< Delta x  movement of left analog-stick
  int8_t  y;         ///< Delta y  movement of left analog-stick
  int8_t  z;         ///< Delta z  movement of right analog-joystick
  int8_t  rz;        ///< Delta Rz movement of right analog-joystick
  int8_t  rx;        ///< Delta Rx movement of analog left trigger
  int8_t  ry;        ///< Delta Ry movement of analog right trigger
  uint8_t hat;       ///< Buttons mask for currently pressed buttons in the DPad/hat
  uint32_t buttons;  ///< Buttons mask for currently pressed buttons
}hid_gamepad_report_t;
```
