### ISSUE TITLE
Dice Roller: Keybind tweaks

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#292]
The ability to press B to roll feels weird, maybe change it to Start? Alternatively, make the different buttons do slow/fast rolls like the reflector swadge.

**Comment by AEFeinstein** [comment]
B to go back makes no sense, and it's better to have the button do something than nothing. Slow rolls are an option, but in hindsight feel kinda dumb. I'm OK with the behavior as-is.

**Comment by Brycey92** [comment]
B to go back definitely wouldn't be the way to go here, and aside from slow rolling, I can't really thing of another thing for it to do. guess changing the buttons would depend on making new features that justify extra buttons first
