### ISSUE TITLE
Platformer

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#30]
- [x] Switch between levels
- [x] Container Blocks drop items
- [x] In-level warps
- [x] Finalize HUD
- [x] Title screen
- [x] Defeating/taking damage from enemies
- [x] Life items
- [x] Power-up ability of some sort
- [x] Scoring/combo system
- [x] Checkpoints
- [x] More enemy types
- [x] Highscore tracking
- [x] More levels
- [x] Sound effects
- [x] Sound effects for 1UP, Checkpoint, and running out of time
- [x] Implement "Underground","Castle", and "Highscore Name Entry" songs (framework is already in place, just need the actual songs)
- [x] Time limit should kill the player
- [x] Finalize ending screen (just text probably, nothing fancy)
- [x] Levels should unlock as the player completes them rather than being unlocked from the beginning

Nice to haves:
(not adding)
moving platforms
on/off blocks, switches, and rollovers
title screen demo

**Comment by AEFeinstein** [comment]
@JVeg199X is this to-do list accurate? I think there's a power-up at least. I know we're still looking to get more levels, but are there any other engine features or bugs you're looking at?

**Comment by JVeg199X** [comment]
I don't have any more major engine changes planned, just a few things to add/polish here and there. And yes, more levels, of course.

**Comment by AEFeinstein** [comment]
Polish polish polish, last week reminder!

**Comment by JVeg199X** [comment]
Please do not delete the branch yet.

**Comment by AEFeinstein** [comment]
You got it boss

**Comment by AEFeinstein** [comment]
Branch is merged and all the items here are checked off, so I'm deleting the branch. If you need to make any more fixes or whatnot, you can make a new branch. Congrats!
