### ISSUE TITLE
Bee/CopyPastas: Infrequent crash when switching texts quickly

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#302]
From @arty01238:
> If you switch between the texts fast/frequently enough, at some point the swadge either stops randomization or crashes. I've only duplicated this 3 times, but 3 is more than 0

**Comment by AEFeinstein** [comment]
I mario-party style spammed the button in the emulator until my forearm hurt and was not able to replicate this. Hardware only bug maybe?

**Comment by Brycey92** [comment]
I spammed Select on hardware, but my arm didn't hurt so maybe I didn't do it right - further details and testing still needed

**Comment by arty01238** [comment]
I also held the up arrow to speed up texts I can attempt to recreate again but it takes me several attempts.

**Comment by arty01238** [comment]
[Thread 28820.0x1220 exited with code 0]
[Thread 28820.0x5d70 exited with code 0]
[Thread 28820.0x89c exited with code 0]

And emulator crashed

**Comment by AEFeinstein** [comment]
That's what a crash would look like, but it isn't enough info for me to debug. If you want to try to crash it again (I still can't), from VSCode launch the emulator with the `F5` key, which will also attach gdb. Then when it crashes you should be able to see the "Call Stack" on the "Run and Debug" tab. Screenshot that and it should pinpoint the issue.
