### ISSUE TITLE
Flyin Donut: Text entry special icons are TINY

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#310]
When entering your name for a high score, the caps, tab, shift, and backspace icons are very small, and were probably never resized from tom_thumb to ibm_vga8

**Comment by cnlohr** [comment]
Hmm, that's fair.  But, perhaps next year.  Actually, next year I might part-out the keyboard so it can be used elsewhere.

**Comment by Brycey92** [comment]
I thought you had already parted it out this year? Looks like it's self-contained in its own c and h files, as far as I can tell from a glance
