### ISSUE TITLE
Swadge Bros: Wireless multi P1 game soft-locks on lost communication

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#312]
In wireless multi, only the p2 swadge returns to the fighter menu when connection is lost. the p1 swadge remains in-game, but inputs do nothing aside from start+select. there is no indication on p1 that there has been a communication issue

**Comment by AEFeinstein** [comment]
This is a consequence of how I rearchitected p2p for speed. p2p is fundamentally an ACKed protocol, and ACKs take time. The speedup came by embedding data in each ACK, so there's a constant back and forth of buttons -> scene -> buttons -> scene without any 'wasted' ACKs. But this means that one side can fall into the "message not ACKed" case and fail out, but the other one never technically sends a p2p packet, so it soft-locks.

I'd have to implement some sort of more overarching timer to check for a constant data stream, and I'm not doing that this weekend, so it is what it is. I think the soft-lock is a pretty good indicator of communications issue.

**Comment by Brycey92** [comment]
Explanation ACKed, we'll see this issue on the other side

**Comment by AEFeinstein** [comment]
Actually, we won't. Fighter and Paint Sharing are modes that **really shoud not** change between 1.0 and 1.1. Cross-version compatibility is more trouble than it's worth. It is what it is.
