### ISSUE TITLE
Tiltrads: Chill mode

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#318]
I saw "no stress tris" in some #defines and such, and thought it would be cool to give very casual gamers options in how they want to play the game. High-score recording would of course either be disabled or separated

**Comment by AEFeinstein** [comment]
Huh, it does exist. I have never seen any tetris-esque game with this option
```C
//#define NO_STRESS_TRIS // Debug mode that when enabled, stops tetrads from dropping automatically, they will only drop when the drop button is pressed. Useful for testing line clears.
```
