### ISSUE TITLE
Swadge Land: End zone doesn't register walking onto it, only landing

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#325]
at the end of level 1-2, you can land on the grass area in front of the end zone and then walk across the zone and jump at your preferred stopping point

**Comment by Brycey92** [comment]
@JVeg199X made it impossible to walk onto any end zones by level design, but this is still a bug in the engine. good news is it no longer affects the shipping firmware!

**Comment by Brycey92** [comment]
Should this still be open, so we know to fix it in the engine? It would prevent the issue from popping back up if someone designs a walkable end zone again

**Comment by AEFeinstein** [comment]
I don't believe @JVeg199X is making engine changes for 1.1, and this could be considered a feature at some point, so I'm inclined to leave it as-is.
