### ISSUE TITLE
Active RAM usage counter

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#382]
Active RAM usage counter in firmware across all modes, similar to the exit functionality. Toggle-able via the secrets menu

**Comment by AEFeinstein** [comment]
Any sort of system monitoring is going to incur some overhead. It's also not trivial to overdraw on the screen (see #380). You'll need to be quite careful with this.

Who is this for anyway? If it's for developers, it's much better to use `ESP_LOGx` and specifically target where memory is measured. I did that when managing fighter sprites, for instance.

**Comment by Brycey92** [comment]
Ah yes, it would be for developers. I wasn't sure whether the emulator had similar enough memory usage to the hardware to be useful that way. If it does, we can close this

**Comment by AEFeinstein** [comment]
What we call an emulator is really more of a simulator, since it's not even trying to accurately emulate things like CPU instructions or memory management. I still stand by targeted `ESP_LOGx` rather than a general overlay.
