### ISSUE TITLE
Compilation issues on macOS - `invalid output constraint '=a' in asm`

### ISSUE THREAD

**Issue by ZachOrr** [AEFeinstein/Super-2023-Swadge-FW#401]
When attempting to run the `make` command I'm running into compilation issues

```
$ make -f emu.mk clean all
...
In file included from emu/src/emu_sensors.c:14:
In file included from main/swadge_esp32.h:5:
main/swadge_util.h:26:34: error: invalid output constraint '=a' in asm
    asm volatile("rsr %0,ccount":"=a" (ccount));
                                 ^
3 warnings and 1 error generated.
make: *** [emu/obj/emu/src/emu_sensors.o] Error 1
```

It seems like macOS isn't able to compile that instruction. People seem to work around it by using an `ifdef` to add a LOC that will compile on macOS - but I'm unsure what the proper code would be here.

https://stackoverflow.com/questions/64035775/invalid-output-constraint-d-in-asm-when-building-glib-for-arm32windows

## Env

Apple M1 Max - so an ARM instruction set

```
$ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
```

**Comment by dylwhich** [comment]
I think that assembly is only intended for the ESP and it's just a coincidence that it has worked on linux/windows so far. The `getCycleCount()` function should probably just have an `#ifdef EMU` and return 0 in that case.

**Comment by AEFeinstein** [comment]
Yeah, the assembly is a happy coincidence. You can comment that out with no ill effect, but you'll eventually find that https://github.com/cntools/rawdraw doesn't support macOS, so compiling the emulator is gonna be a dead end. Targeting WASM might work, but no one's gone down that path.

Compiling the firmware with ESP IDF _should_ still work on macOS, but I don't have the hardware to try that either.

**Comment by ZachOrr** [comment]
Thanks for the help y’all!
