### ISSUE TITLE
Port Tiltrads

### ISSUE THREAD

**Issue by AEFeinstein** [AEFeinstein/Super-2023-Swadge-FW#42]

**Comment by Brycey92** [comment]
See https://github.com/AEFeinstein/Super-2023-Swadge-FW/issues/31#issuecomment-1221395802 for my notes from porting Tunernome.

**Comment by AEFeinstein** [comment]
@jt-moriarty is there anything left to do for Tiltrads? If not, please close this ticket and delete the branch (https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/tiltrads)

**Comment by jt-moriarty** [comment]
TODO: 
-Add gameplay music.
-Confirm menu button remaps meet expectations.

**Comment by AEFeinstein** [comment]
"Select to Title" "Start to Restart"
after finishing the game
