### ISSUE TITLE
qma7981 does not compile

### ISSUE THREAD

**Issue by Brycey92** [AEFeinstein/Super-2023-Swadge-FW#51]
`Super-2023-Swadge-FW/main/swadge_esp32.c:363: undefined reference to 'qma7981_init'`
`Super-2023-Swadge-FW/main/swadge_esp32.c:421: undefined reference to 'qma7981_get_acce_int'
collect2.exe: error: ld returned 1 exit status`

**Comment by AEFeinstein** [comment]
Easy fix, just gotta add stubs to the emu. More troubling, the CI passed a build that definitely failed...
https://app.circleci.com/pipelines/github/AEFeinstein/Super-2023-Swadge-FW/202/workflows/93356eec-805e-4b5d-9b59-570389882100/jobs/74

**Comment by AEFeinstein** [comment]
Fixed in e5da29ff13366237798377060c8b15f05b4c60d9
