### ISSUE TITLE
Investigate why FreeRTOS is eating our lunch

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Super-2023-Swadge-FW#92]
On flight sim, it can be really clear, sometimes freertos just causes the processor to go to sleep for 10ms every frame for some reason.

**Comment by AEFeinstein** [comment]
See `CONFIG_FREERTOS_HZ=100`

**Comment by Brycey92** [comment]
Can this be closed since it was discovered the issue was having a task-ified main loop?

**Comment by AEFeinstein** [comment]
Fixed in be1ed5906abdc2c43b6923f062043b739c8d2050
